// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTxxHzCjHw_dpyL6suiOBKaVqIXQvSyXI',
    appId: '1:881378120945:web:17a3bec48967abdb5d0550',
    messagingSenderId: '881378120945',
    projectId: 'ecommerce-4bba2',
    authDomain: 'ecommerce-4bba2.firebaseapp.com',
    storageBucket: 'ecommerce-4bba2.firebasestorage.app',
    measurementId: 'G-HRGFTSBJP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGifHEyH4lznx6WqeIyNUSSDYySqPXvjY',
    appId: '1:881378120945:android:6071a375947d20a95d0550',
    messagingSenderId: '881378120945',
    projectId: 'ecommerce-4bba2',
    storageBucket: 'ecommerce-4bba2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzcdiip86KcuvErZ-1jc7vm5rzFVTxubc',
    appId: '1:881378120945:ios:9162c9a6d6a07e0e5d0550',
    messagingSenderId: '881378120945',
    projectId: 'ecommerce-4bba2',
    storageBucket: 'ecommerce-4bba2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzcdiip86KcuvErZ-1jc7vm5rzFVTxubc',
    appId: '1:881378120945:ios:9162c9a6d6a07e0e5d0550',
    messagingSenderId: '881378120945',
    projectId: 'ecommerce-4bba2',
    storageBucket: 'ecommerce-4bba2.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTxxHzCjHw_dpyL6suiOBKaVqIXQvSyXI',
    appId: '1:881378120945:web:c49e951681c072d85d0550',
    messagingSenderId: '881378120945',
    projectId: 'ecommerce-4bba2',
    authDomain: 'ecommerce-4bba2.firebaseapp.com',
    storageBucket: 'ecommerce-4bba2.firebasestorage.app',
    measurementId: 'G-SXT8G84CY7',
  );
}
